POST https://dev-jr-node.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###


GET https://dev-jr-node.onrender.com/videos

###

PUT https://dev-jr-node.onrender.com/videos/ade60b96-b9d4-428f-a754-2ab27b5606a4
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE https://dev-jr-node.onrender.com/videos/eef313ba-dd6e-4da8-8f5d-858f703290b3